# Generated by Django 2.1.2 on 2018-11-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=250)),
                ('ratio', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmanager.Leaders')),
            ],
        ),
    ]
