# Generated by Django 2.1.2 on 2018-11-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0002_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages',
            name='leader',
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
